version: "3.7"

services:
  gainz-application:
    container_name: gainz-dev
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./client:/app
  ts-node-docker:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./server/src:/home/node/app/src
      - /home/node/app/node_modules/
      - ./server/nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=postgresdb
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
