version: "3.7"

services:
  gainz-application-prod:
    container_name: gainz-prod
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "1337:80"
  ts-node-docker:
    build:
      target: production
      context: ./server
      dockerfile: Dockerfile
    command: node build/index.js
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=postgresdb
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
