version: "3.7"

services:
  gainz-application-prod:
    container_name: gainz-prod
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "1337:80"
  ts-node-docker:
    build:
      target: production
    command: node build/index.js
